name: Create Live 3klive fork release

on:
  push:
    tags: [ 'v*' ] 

jobs:
  release:
    runs-on: s0-default
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Livego 3klive fork ${{ steps.get_version.outputs.VERSION }}"

  container:
    runs-on: s0-kaniko
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Create container
        run: |
          export DOCKERHUB_AUTH="$(echo -n mlody3k:$DOCKERHUB_TOKEN | base64)"
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"${DOCKERHUB_AUTH}\"}, \"registry.hub.docker.com\":{\"auth\":\"${DOCKERHUB_AUTH}\"}}}" > /kaniko/.docker/config.json
          sudo -E /kaniko/executor --use-new-run --context=dir://$GITHUB_WORKSPACE --dockerfile Dockerfile --destination "$GITHUB_REPOSITORY:${{ steps.get_version.outputs.VERSION }}"
